export const _id = (index: number) => `e99f09a7-dd88-49d5-b1c8-1daf80c2d7b${index}`;

export const _times = (index: number) =>
  // 'MM/DD/YYYY'
  [
    '11/08/2023',
    '04/09/2024',
    '09/12/2023',
    '01/01/2024',
    '04/23/2024',
    '02/29/2024',
    '05/14/2024',
    '01/13/2024',
    '06/22/2024',
    '10/05/2023',
    '07/11/2024',
    '05/22/2024',
    '03/29/2024',
    '08/29/2023',
    '11/19/2023',
    '10/24/2023',
    '12/02/2023',
    '02/13/2024',
    '09/19/2023',
    '04/17/2024',
    '12/18/2023',
    '06/27/2024',
    '10/19/2023',
    '08/09/2024',
  ][index];

  export const _fullName = (index: number) =>
    [
      'Sebastian Martinez Pabón',
      'Anyela Maria Herrera Lobo',
      'Teresa Anne Luettgen Williams',
      'Salvador Miguel Mayert Gonzalez',
      'Dr. Guadalupe Rafael Rath Martinez',
      'Kelvin Alexander Pouros Fernandez',
      'Thelma Victoria Langworth Ortega',
      'Kristen Elizabeth Wunsch Castro',
      'Steve Jonathan Welch Ramirez',
      'Brian Christopher Jacobs Herrera',
      'Lillie Patricia Schultz Torres',
      'Mr. Conrad Benjamin Spinka Morales',
      'Charlene Isabella Krajcik Dominguez',
      'Kerry Matthew Kuhlman Mendoza',
      'Betty Veronica Hammes Vasquez',
      'Tony Leonardo Paucek PhD Rojas',
      'Sherri Gabriela Davis Navarro',
      'Angel Eduardo Rolfson-Kulas Suarez',
      'Dr. Lee Sebastian Doyle-Grant Pacheco',
      'Cheryl Samantha Romaguera Ortiz',
      'Billy Nathan Braun Espinoza',
      'Adam Nicolas Trantow Jimenez',
      'Brandon Andres Von Castillo',
      'Willis Antonio Ankunding Chavez',
    ][index];
  
  export const _semestre=(index: number)=>
  [
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
  ][index];

export const _boolean = (index: number) =>
  [
    true,
    false,
    true,
    false,
    true,
    true,
    true,
    false,
    false,
    true,
    false,
    true,
    true,
    false,
    true,
    false,
    false,
    true,
    false,
    false,
    false,
    true,
    true,
    false,
  ][index];
  export const _riesgo = (index: number)=>
    [
      'bajo',
      'medio',
      'alto',
      'bajo',
      'medio',
      'alto',
      'bajo',
      'medio',
      'alto',
      'bajo',
      'medio',
      'alto',
      'bajo',
      'medio',
      'alto',
      'bajo',
      'medio',
      'alto',
      'bajo',
      'medio',
      'alto',
      'bajo',
      'medio',
      'alto',
    ][index];

   